version: "3"
services:
  backend:
    image: zafaraliinamdar/house-rent-backend
    container_name: backend
    ports:
      - "5000:4000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
